INSERT INTO clientes (nome, cidade, uf) VALUES
('Ana Silva', 'São Paulo', 'SP'),
('João Santos', 'Rio de Janeiro', 'RJ'),
('Maria Oliveira', 'Belo Horizonte', 'MG'),
('Carlos Pereira', 'Curitiba', 'PR'),
('Fernanda Costa', 'Porto Alegre', 'RS'),
('Lucas Almeida', 'Salvador', 'BA'),
('Juliana Martins', 'Fortaleza', 'CE'),
('Rafael Gomes', 'Brasília', 'DF'),
('Camila Lima', 'Recife', 'PE'),
('Thiago Rocha', 'Manaus', 'AM'),
('Sofia Alves', 'Natal', 'RN'),
('Marcos Lima', 'Belém', 'PA'),
('Tatiane Ribeiro', 'Goiânia', 'GO'),
('Bruno Dias', 'Vitória', 'ES'),
('Aline Souza', 'Maceió', 'AL'),
('Felipe Mendes', 'Campo Grande', 'MS'),
('Vanessa Cardoso', 'João Pessoa', 'PB'),
('Roberto Nascimento', 'Aracaju', 'SE'),
('Natália Pires', 'Teresina', 'PI'),
('Eduardo Castro', 'Florianópolis', 'SC'),
('Simone Ferreira', 'Cuiabá', 'MT');
